import { motion } from 'framer-motion';
import { FileText } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-neutral-50 dark:bg-neutral-950 py-12 px-4 sm:px-6 lg:px-8">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl mx-auto space-y-8">
        <div className="text-center space-y-4">
          <FileText size={48} className="mx-auto text-purple-600" />
          <h1 className="text-4xl font-extrabold tracking-tight text-neutral-900 dark:text-white">Terms of Service</h1>
          <p className="text-lg text-neutral-500">The rules governing the use of OmnibusAI.</p>
        </div>

        <div className="bg-white dark:bg-neutral-900 rounded-3xl shadow-xl border border-neutral-200 dark:border-neutral-800 p-8 md:p-12 prose dark:prose-invert max-w-none">
          <h3>1. Acceptance of Terms</h3>
          <p>By accessing OmnibusAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the application.</p>
          
          <h3>2. User Responsibilities</h3>
          <p>You are responsible for maintaining the security of your account, including your passwords and Two-Factor Authentication codes. You agree not to use the AI to generate malicious code, engage in illegal activities, or violate the rights of others.</p>

          <h3>3. API Usage & Limitations</h3>
          <p>Developer accounts are subject to rate limiting. OmnibusAI provides responses generated by Large Language Models; these models can make mistakes. You must verify important information and code before deploying it to production environments.</p>

          <p className="text-sm text-neutral-400 mt-8 pt-8 border-t border-neutral-200 dark:border-neutral-800">Last updated: July 2026</p>
        </div>
      </motion.div>
    </div>
  );
}